In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
print(y)

tensor([[0.9039, 0.6470, 0.3069, 0.2567, 0.1579],
        [0.2874, 0.3081, 0.7451, 0.9370, 0.5123]])


In [6]:
y.view([1,10])

tensor([[0.9039, 0.6470, 0.3069, 0.2567, 0.1579, 0.2874, 0.3081, 0.7451, 0.9370,
         0.5123]])

In [7]:
y

tensor([[0.9039, 0.6470, 0.3069, 0.2567, 0.1579],
        [0.2874, 0.3081, 0.7451, 0.9370, 0.5123]])

In [8]:
y = y.view([1,10])

In [9]:
y

tensor([[0.9039, 0.6470, 0.3069, 0.2567, 0.1579, 0.2874, 0.3081, 0.7451, 0.9370,
         0.5123]])